name: CI

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: isort
      run: python -m  isort . --check --diff
    - name: black
      run: python -m black --check --diff .
    - name: flake8
      run: python -m flake8 .
    - name: mypy
      run: |
        python -m mypy openmapflow
        python -m mypy tests
        python -m mypy buildings-example/*.py
        python -m mypy crop-mask-example/*.py
        python -m mypy maize-example/*.py
    - name: unittest
      run: python -m unittest discover -s tests
