name: Deploy

on:
  push:
    branches: [ main ]
    paths:
    - 'crop-mask-example/**'

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: pip install -e .
    - uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true   
    - uses: iterative/setup-dvc@v1
    - name: Deploy Google Cloud Architecture
      env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      run: |
        cd crop-mask-example
        chmod +x ./deploy.sh
        ./deploy.sh