name: Build and push docker

on:
  push:
    branches: [ main ]
    paths:
    - 'docker/**'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout openmapflow
        uses: actions/checkout@v2
      - name: Login to Docker
        env:
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login --username ivanzvonkov --password "$DOCKER_PASSWORD"
      - name: Push Docker Nightly
        run: |
          cd docker
          docker build .
          docker tag ivanzvonkov/openmapflow
          docker push ivanzvonkov/openmapflow
